language: ruby
rvm:
  - 2.6.5
install:
  - time bundle install --without production --deployment --jobs=4
script:
  - time bundle exec rake
notifications:
  email:
    on_success: never
sudo: false
cache:
  apt: true
  directories:
  - vendor/bundle
