language: ruby
rvm:
  - 2.1.0
  - 2.2.3
  - 2.3.0
  - 2.3.1
install:
  - time bundle install --without production --deployment --jobs=4
script:
  - time bundle exec rake
notifications:
  email:
    on_success: never
sudo: false
cache:
  apt: true
  directories:
  - vendor/bundle
