#! /usr/bin/zsh

cd ~/codes/nna774-middleman

TITLE=$@

echo $TITLE

if [ -z $TITLE ];then
    echo input title
    exit 1
fi


FILE=`bundle exec middleman article $TITLE | tail -n1 | awk '{print $2}'`

emacs $FILE

bundle exec middleman build

if [ ! $? ];then
   echo build failure! >&2
   exit 1
fi

git add $FILE

git commit

cd build

git add .

git commit # -m `cat ../.git/COMMIT_EDITMSG`

git push

cd ..

#rsync -avz --exclude=".git/" -e 'ssh -p 10044' build/ pi:/var/www from "."

bundle exec middleman deploy

