version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.6-buster
    working_directory: ~/workdir
    steps:
      - checkout
      - run: apt update
      - run: apt install -y nodejs
      - run: ruby -v
      - restore_cache:
          name: Restoring Cache - Bundler
          keys:
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-
      - run: bundle install --path=vendor/bundle --without development
      - run: bundle exec rake build
      - save_cache:
          name: Saving Cache - Bundler
          key: gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
  deploy:
    docker:
      - image: ruby:2.6-buster
    working_directory: ~/workdir
    steps:
      - run: echo "export PATH='$PATH:~/bin'" >> $BASH_ENV
      - aws-s3/sync:
          from: build
          to: s3://nna774.net
          arguments: --delete
          overwrite: true

orbs:
  aws-s3: circleci/aws-s3@1.0.11

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
