version: 2
jobs:
  build:
    docker:
      - image: nna774/ruby:2.4.3-node-with-rsync
    steps:
      - checkout
      - run: ruby -v
      - restore_cache:
          name: Restoring Cache - Bundler
          keys:
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-
      - run: bundle install --path=vendor/bundle --without development
      - run: bundle exec rake build
      - save_cache:
          name: Saving Cache - Bundler
          key: gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run: echo "|1|4JQqHDZJVuU3DkRIhiAUcNdIMAc=|OiIZfr7NGN2aXUINmWBICq65Dbs= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDq/akxyvBB6JrS+eTmZja1R/U41Pn30FgZbsQ3UBKLxWNU3WAUxJKZL4ZDDt7TB8XTP2PWFeTZGvbjYR3MOBms=" | tee -a ~/.ssh/known_hosts
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sed -i -e "s/deploy.user          = 'nona'/deploy.user = 'circleci'/" config.rb
              bundle exec rake deploy
            fi
